services:
  to-do-list:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/opt/to-do-list"
      - "/opt/to-do-list/node_modules"
    environment:
      - NEXT_WEBPACK_USEPOLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true